### ISSUE TITLE
Resolve doesn't resolve real path for `basedir` if it is relative path

### ISSUE THREAD

**Issue by malash** [browserify/resolve#177]
`resolve` doesn't resolve real path for `basedir` if it is relative path.

I'v created a bad case example ( by [lerna](https://github.com/lerna/lerna) ) here https://github.com/malash/resolve-bad-case

The issue is related to https://github.com/browserify/resolve/issues/130 .
The issue effected https://github.com/peerigon/extract-loader/issues/48 and may affect https://github.com/browserify/resolve/issues/163 .

@zkochan @ljharb

**Comment by ljharb** [comment]
It seems like you're not setting the `preserveSymlinks` option to `false`, (it currently defaults to `true` in v1, altho master has the breaking change of defaulting it to `false`).

What happens if you set that option?

**Comment by malash** [comment]
I update the test case and the bug still exists. 

https://github.com/malash/resolve-bad-case/commit/c5ea1c8d577bd35ecb586ad82d16b54499893be7

In fact `preserveSymlinks` isn't used at all in https://github.com/browserify/resolve/blob/master/lib/sync.js#L49-L52

**Comment by ljharb** [comment]
hmm, i'm trying to reproduce this error, and i do get this failure: 
`Cannot find module '../../node_modules/jquery' from './node_modules/@my-scope/package-b'`

However, after `npm install` *and* after `npx lerna bootstrap`, `node_modules` still lacks a `@my-scope` directory, so i'm not sure why you'd expect something to be resolved there.

**Comment by malash** [comment]
@ljharb I will clarify it. 

When running `node packages/package-a` 

it equals to 

`cd packages/package-a && node ./index.js` 

so the `basedir` would be 

`the-repo/packages/package-a/node_modules/@my-scope/package-b`

which is a symlink to `the-repo/packages/package-b`.

> There is a real issue when I use `webpack` with `extract-loader` https://github.com/peerigon/extract-loader/issues/48#issuecomment-441891920

**Comment by ljharb** [comment]
OK, but the error says "from node_modules/@my-scope/package-b" - and then "../../node_modules/jquery'" - so, the final path it's looking for is "node_modules/jquery" (inside package-a) - but package-a doesn't have jquery listed as a dependency, and it's not present on disk.

**Comment by ljharb** [comment]
(and package-b doesn't have jquery either)

**Comment by malash** [comment]
No. The final path is not `'node_modules/jquery'` but `'packages/package-a/node_modules/node_modules/jquery'` and it's wrong even if `package-a` had `jquery`.

---

First, I fixed [the `basedir` in test case with abs path](https://github.com/malash/resolve-bad-case/blob/e444fc2f35a9210f7cae75cd537a4e5895edabda/packages/package-a/index.js#L5) so the error trace is more clear.

```
/Users/malash/Projects/resolve-bad-case/node_modules/jquery/dist/jquery.js
/Users/malash/Projects/resolve-bad-case/node_modules/resolve/lib/sync.js:46
    throw err;
    ^

Error: Cannot find module '../../node_modules/jquery' from '/Users/malash/Projects/resolve-bad-case/packages/package-a/node_modules/@my-scope/package-b'
    at Function.module.exports [as sync] (/Users/malash/Projects/resolve-bad-case/node_modules/resolve/lib/sync.js:44:15)
    at Object.<anonymous> (/Users/malash/Projects/resolve-bad-case/packages/package-a/index.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

---

The current logic equals to `path.resolve` because of [this line ](https://github.com/browserify/resolve/blob/master/lib/sync.js#L49) :

`'/path/to/repo/packages/package-a/node_modules/@my-scope/package-b'` 
+
 `'../../node_modules/jquery'`
 =>
`'/path/to/repo/packages/package-a/node_modules/node_modules/jquery'`

It's a non-exist path.

The correct way should be:

1. Get the real path of `basedir`. E.g.  

`'/path/to/repo/packages/package-a/node_modules/@my-scope/package-b'` =>  
`'/path/to/repo/packages/package-b/'`

2. Resolve the path. 

`'/path/to/repo/packages/package-b/'` + `'../../node_modules/jquery'` => 
`/path/to/repo/node_modules/jquery`

That line could be refactor like this ( just for demo ):

```js
// if not preserveSymlinks
path.resolve(fs.realpathSync(basedir), x)
// else
path.resolve(basedir, x)
```

> `fs.realpathSync` will handle the `basedir` if it is a symlink ( even inside a symlink ).

**Comment by ljharb** [comment]
Got it, thanks for explaining.

**Comment by ljharb** [comment]
OK, so part of the problem is that the basedir you're passing in isn't resolved - it's relative to package-a/index, but that's not information that resolve can retain - so you first have to `path.resolve(__dirname, './node_modules/@my-scope/package-b')`.

This makes the first assertion pass, but the second still fails for me.

**Comment by malash** [comment]
Normally the `basedir` should be absolute path. It's my fault to pass a relative path for `basedir` in the first version test case so I fixed it. That could be another good question how relative `basedir` resolved.

For this issue the inconsistency is that user have to resolve real path of basedir for relative path but not NPM package.

```js
console.log(resolve.sync("jquery", { basedir: basedir }));
console.log(resolve.sync("../../node_modules/jquery", { basedir: fs.realpathSync(basedir) }));
```

**Comment by ljharb** [comment]
I think maybe because the relative path isn’t ../../node_modules, it’s just ./node_modules? (Without the realpathsync in the second line)

**Comment by malash** [comment]
Compression between `preserveSymlinks === true` and `preserveSymlinks === false`

```js
// preserveSymlinks === false
// will search NPM package from
// * packages/package-b/node_modules
// * packages/node_modules
// * node_modules
console.log(resolve.sync('jquery', { basedir: basedir, preserveSymlinks: false }));
console.log(resolve.sync('../../node_modules/jquery', { basedir: fs.realpathSync(basedir), preserveSymlinks: false }));

// preserveSymlinks === true
// will search NPM package from
// * packages/package-a/node_modules/@my-scope/packages/package-b/node_modules
// * packages/package-a/node_modules/@my-scope/packages/node_modules
// * packages/package-a/node_modules/@my-scope/node_modules
// * packages/package-a/node_modules/node_modules
// * packages/package-a/node_modules
// * packages/node_modules
// * node_modules
console.log(resolve.sync('jquery', { basedir: basedir, preserveSymlinks: true }));
console.log(resolve.sync('../../../../../node_modules/jquery', { basedir: basedir, preserveSymlinks: true }));

```

**Comment by malash** [comment]
@ljharb Thank you very much for your commit. [This commit](https://github.com/browserify/resolve/commit/2321cd4b4e184f9c97f76ea50dd49b9e42927b93) works for me.

**Comment by ljharb** [comment]
Thank you for your excellent repro case!

**Comment by john-kurkowski** [comment]
> It seems like you're not setting the `preserveSymlinks` option to `false`, (it currently defaults to `true` in v1, altho master has the breaking change of defaulting it to `false`).

Did this breaking change get resolved before publishing v1.9.0?

`master` (04e6c79) has a different check

https://github.com/browserify/resolve/blob/04e6c7929a1b3b5c3698f802597eb0fbccf4411a/lib/async.js#L57

vs. what I think was published at tag v1.9.0.

https://github.com/browserify/resolve/blob/v1.9.0/lib/sync.js#L36

**Comment by ljharb** [comment]
@john-kurkowski v1.9.0 does not include any of the breaking changes. I cherry-picked commits onto the v1.8.1 tag, and released, and merged the v1.9.0 tag back to master.

**Comment by ljharb** [comment]
@simonhaenisch it’s released in v1.9.0. If you’re still seeing a problem, please file a new issue and we can talk it out there.
